name: Build/release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build
        run: msbuild YATinyWinFTP.sln /p:Configuration=Release /p:Platform=x86

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          # GitHub token, automatically provided to the action
          repo_token: ${{ secrets.github_token }}
          file: "bin/Release/x86/*.exe"
          tag: ${{ github.ref }}
          overwrite: true
          #asset_name: "app-${{ matrix.platform }}.exe"
