name: Build/release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Clone Asio headers
        run: pwd; git clone --depth 1 https://github.com/chriskohlhoff/asio.git
        working-directory: .
  
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)' 

      - name: Build
        run: msbuild YATinyWinFTP.sln /p:Configuration=Release /p:Platform=x86

      - name: List files recursively
        run: |
          echo "::group::Current directory files"
          ls -R
          echo "::endgroup::"

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          # GitHub token, automatically provided to the action
          repo_token: ${{ secrets.github_token }}
          file: "Release/*.exe"
          tag: ${{ github.ref }}
          overwrite: true
          #asset_name: "app-${{ matrix.platform }}.exe"
